// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package gameplay

func MergePlayerBasicCom(a map[string]PlayerBasicCom, b map[string]PlayerBasicCom) map[string]PlayerBasicCom {
	ret := map[string]PlayerBasicCom{}
	for k, v := range a {
		ret[k] = v
	}
	for k, v := range b {
		ret[k] = v
	}
	return ret
}
