// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package gameplay

// MergeCharacterCardCom is
func MergeCharacterCardCom(a map[string]CharacterCardCom, b map[string]CharacterCardCom) map[string]CharacterCardCom {
	ret := map[string]CharacterCardCom{}
	for k, v := range a {
		ret[k] = v
	}
	for k, v := range b {
		ret[k] = v
	}
	return ret
}
