// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package gameplay

import "fmt"

// FilterPlayer is
func FilterPlayer(s1 []Player, f func(Player) bool) []Player {
	ret := []Player{}
	for _, v := range s1 {
		if f(v) {
			ret = append(ret, v)
		}
	}
	return ret
}

// RemovePlayer is
func RemovePlayer(s1 []Player, card Player) ([]Player, error) {
	findID := -1
	for _findID, c := range s1 {
		if c == card {
			findID = _findID
			break
		}
	}
	if findID == -1 {
		return s1, fmt.Errorf("item not found")
	}
	s1 = append(s1[0:findID], s1[findID+1:]...)
	return s1, nil
}

// ReplacePlayer is
func ReplacePlayer(items []Player, info map[Player]Player) []Player {
	ret := make([]Player, len(items))
	copy(ret, items)
	for origin, next := range info {
		for idx, card := range items {
			if card == origin {
				ret[idx] = next
			}
		}
	}
	return ret
}
