// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package gameplay

// KesStringCharacterCardCom is
func KesStringCharacterCardCom(dict map[string]CharacterCardCom) []string {
	ret := make([]string, 0, len(dict))
	for k := range dict {
		ret = append(ret, k)
	}
	return ret
}

// ValsStringCharacterCardCom is
func ValsStringCharacterCardCom(dict map[string]CharacterCardCom) []CharacterCardCom {
	ret := make([]CharacterCardCom, 0, len(dict))
	for _, v := range dict {
		ret = append(ret, v)
	}
	return ret
}

// MergeStringCharacterCardCom is
func MergeStringCharacterCardCom(a map[string]CharacterCardCom, b map[string]CharacterCardCom) map[string]CharacterCardCom {
	ret := map[string]CharacterCardCom{}
	for k, v := range a {
		ret[k] = v
	}
	for k, v := range b {
		ret[k] = v
	}
	return ret
}

// AssocStringCharacterCardCom is
func AssocStringCharacterCardCom(a map[string]CharacterCardCom, k string, v CharacterCardCom) map[string]CharacterCardCom {
	ret := map[string]CharacterCardCom{}
	for k, v := range a {
		ret[k] = v
	}
	ret[k] = v
	return ret
}
