// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package gameplay

// KesStringPlayerBasicCom is
func KesStringPlayerBasicCom(dict map[string]PlayerBasicCom) []string {
	ret := make([]string, 0, len(dict))
	for k := range dict {
		ret = append(ret, k)
	}
	return ret
}

// ValsStringPlayerBasicCom is
func ValsStringPlayerBasicCom(dict map[string]PlayerBasicCom) []PlayerBasicCom {
	ret := make([]PlayerBasicCom, 0, len(dict))
	for _, v := range dict {
		ret = append(ret, v)
	}
	return ret
}

// MergeStringPlayerBasicCom is
func MergeStringPlayerBasicCom(a map[string]PlayerBasicCom, b map[string]PlayerBasicCom) map[string]PlayerBasicCom {
	ret := map[string]PlayerBasicCom{}
	for k, v := range a {
		ret[k] = v
	}
	for k, v := range b {
		ret[k] = v
	}
	return ret
}

// AssocStringPlayerBasicCom is
func AssocStringPlayerBasicCom(a map[string]PlayerBasicCom, k string, v PlayerBasicCom) map[string]PlayerBasicCom {
	ret := map[string]PlayerBasicCom{}
	for k, v := range a {
		ret[k] = v
	}
	ret[k] = v
	return ret
}
