/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * WebTest.ls
 */
export class RuntimeScriptBase extends Laya.Scene {
    public BtnCallWeb!: Laya.Button;
}

