<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>App1</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AdAutomation.Core\AdAutomation.Core.fsproj" />
    <ProjectReference Include="..\AdAutomation.Runner\AdAutomation.Runner.fsproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="DemoAdPlatform.fs" />
    <Compile Include="Program.fs" />
  </ItemGroup>

</Project>
