version: "3"
services:
  # https://stackoverflow.com/questions/64247833/how-to-proxy-pass-api-path-to-port-with-nginx
  web:
    image: nginx:1.25
    volumes: 
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      #- ./client/public:/www/data
      #- ./client/out:/www/data/out
      - ./client:/www/data
      #- ./client2:/www/data
      #- ./client3/public:/www/data
    ports:
      - 8080:8080
  api:
    image: clojure
    working_dir: /han
    volumes:
      - ./game:/han
    ports:
      - 8081:8081
    command: clj -X:server
  # docker-compose run --name dev-project7-clojureDev clojure bash
  clojure:
    image: clojure
    working_dir: /han
    volumes:
      - ./:/han
  # docker-compose run --name dev-project7-clojureDev-dotnet dotnet bash
  # https://fable.io/docs/getting-started/your-first-fable-project.html
  dotnet:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    working_dir: /han
    volumes:
      - ./:/han
  # docker-compose run --rm elm init
  # docker-compose run --rm elm install elm/json
  # docker-compose run --rm elm make src/Main.elm --optimize --output=public/elm.js
  elm:
    image: codesimple/elm:0.19
    working_dir: /han
    volumes:
      - ./client3:/han