version: "3"
services:
  # https://stackoverflow.com/questions/64247833/how-to-proxy-pass-api-path-to-port-with-nginx
  web:
    image: nginx:1.25
    volumes: 
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./client/public:/www/data
      - ./client/out:/www/data/out
    ports:
      - 8080:8080
  api:
    image: clojure
    working_dir: /han
    volumes:
      - ./game:/han
    ports:
      - 8081:8081
    command: clj -X game.server/-main
  # docker-compose run --name dev-project7-clojureDev clojure bash
  clojure:
    image: clojure
    working_dir: /han
    volumes:
      - ./:/han