# sdxli能跑, 但zit跑不動
services:
  comfyui:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: comfyui
    ports:
      - "8188:8188"
    volumes:
      - C:\\Users\\johny\\Documents\\ComfyUI-master\\ComfyUI-master\\models:/root/ComfyUI/models
      - ./output:/root/ComfyUI/output
      - ./input:/root/ComfyUI/input
      - ./custom_nodes:/root/ComfyUI/custom_nodes
    deploy:
      resources:
        limits:
          cpus: '4.0'              # 限制最多使用 4 個 CPU 核心
          memory: 48G              # 限制容器最大實體記憶體為 16 GB
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]