version: "3"
services:
  # docker-compose run --rm elm init
  # docker-compose run --rm elm make src/Main.elm --optimize --output=public/elm.js
  elm:
    image: codesimple/elm:0.19
    working_dir: /han
    volumes:
      - ./:/han
  # docker-compose run --rm http-server node_modules/http-server/bin/http-server -c-1 -p 8080
  http-server:
    build: docker-script/http-server/
    working_dir: /han
    volumes:
      - ./public:/han/public
    ports:
      - 8080:8080
    command: node_modules/http-server/bin/http-server -c-1 -p 8080
  http-server2:
    image: nginx:1.25
    volumes: 
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./public:/han/public
    ports:
      - 8081:8081