// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package ui_data

// KesIntInt is
func KesIntInt(dict map[int]int) []int {
	ret := make([]int, 0, len(dict))
	for k := range dict {
		ret = append(ret, k)
	}
	return ret
}

// ValsIntInt is
func ValsIntInt(dict map[int]int) []int {
	ret := make([]int, 0, len(dict))
	for _, v := range dict {
		ret = append(ret, v)
	}
	return ret
}

// MergeIntInt is
func MergeIntInt(a map[int]int, b map[int]int) map[int]int {
	ret := map[int]int{}
	for k, v := range a {
		ret[k] = v
	}
	for k, v := range b {
		ret[k] = v
	}
	return ret
}

// AssocIntInt is
func AssocIntInt(a map[int]int, k int, v int) map[int]int {
	ret := map[int]int{}
	for k, v := range a {
		ret[k] = v
	}
	ret[k] = v
	return ret
}
