/*
 * This Scala source file was generated by the Gradle 'init' task.
 */
package project.app

import project.utilities.StringUtils

import org.apache.commons.text.WordUtils

import com.google.ads.googleads.lib.GoogleAdsClient
import com.google.ads.googleads.lib.utils.FieldMasks
import com.google.ads.googleads.v13.enums.{AdGroupAdStatusEnum, AdGroupStatusEnum}
import com.google.ads.googleads.v13.errors.GoogleAdsException
import com.google.ads.googleads.v13.resources.{AdGroup, AdGroupAd}
import com.google.ads.googleads.v13.services._
import com.google.ads.googleads.v13.utils.ResourceNames
import com.google.auth.oauth2.UserCredentials

import scala.jdk.CollectionConverters._

object App {
   def main(args: Array[String]): Unit = {
        val clientId = ""
        val clientSecret = ""
        val developerToken = ""
        val refreshToken = ""
        val managerCustomerId = ""
        val credential = UserCredentials.newBuilder()
            .setClientId(clientId)
            .setClientSecret(clientSecret)
            .setRefreshToken(refreshToken)
            .build()
        val googleAdsClient = GoogleAdsClient.newBuilder()
            .setDeveloperToken(developerToken)
            .setCredentials(credential)
            .setLoginCustomerId(managerCustomerId.toLong)
            .build()
        // ====================== step 1
        // 用managerCustomerId取得customerId
        if(false) {
            val query =
            s"""
                |SELECT customer_client.id
                |     , customer_client.descriptive_name
                |     , customer_client.client_customer
                |     , customer_client.resource_name
                |     , customer_client.level
                |FROM customer_client
                |""".stripMargin.trim
            val googleAdsServiceClient = googleAdsClient.getVersion13.createGoogleAdsServiceClient()
            val r = googleAdsServiceClient.search(
                SearchGoogleAdsRequest.newBuilder()
                    .setQuery(query)
                    .setCustomerId(managerCustomerId)
                    .build()
            )
            val v = r.iterateAll().asScala.map { row => row }.toVector
            v.foreach { row => 
                println("===========")
                println(row)
                val cc = row.getCustomerClient
                val customerId = cc.getId
                val name = cc.getDescriptiveName
                println(s"customerId = ${customerId}")
                println(s"name = ${name}")
            }
            println(v.length)
        }
        // === DAC_メナード化粧品
        val customerId = "7575378147"
        // === DAC_HDY_LGエレクトロニクス
        // val customerId = "8778793393"


        // ====================== step2
        // 用customerId取得campaignId
        if(false){
            val query = s"""
                |SELECT campaign.id
                |     , campaign.name
                |     , campaign.status
                |     , campaign.start_date
                |     , campaign.end_date
                |FROM campaign
                |""".stripMargin.trim
            val googleAdsServiceClient = googleAdsClient.getVersion13.createGoogleAdsServiceClient()
            val r = googleAdsServiceClient.search(
                SearchGoogleAdsRequest.newBuilder()
                    .setQuery(query)
                    .setCustomerId(customerId)
                    .build()
            )
            val v = r.iterateAll().asScala.map { row => row }.toVector
            v.foreach { row => 
                println("===========")
                println(row)
                val cc = row.getCampaign
                println(s"name = ${cc.getName}")
            }
            println(v.length)
        }
        // === DAC_メナード化粧品
        val campaignId = 19868462058L
        // === 花粉連動_やや多い以上_東北_20230323-20230430
        // val campaignId = 19775953105L


        // ====================== step 3
        // 用campaignId取得adGroupId
        if(true){
            val query = s"""
             |SELECT ad_group.id
             |     , ad_group.name
             |     , ad_group.status
             |FROM ad_group
             |WHERE campaign.id = ${campaignId}
             |""".stripMargin.trim
            val googleAdsServiceClient = googleAdsClient.getVersion13.createGoogleAdsServiceClient()
            val r = googleAdsServiceClient.search(
                SearchGoogleAdsRequest.newBuilder()
                    .setQuery(query)
                    .setCustomerId(customerId)
                    .build()
            )
            val v = r.iterateAll().asScala.map { row => row }.toVector
            v.foreach { row => 
                println("===========")
                println(row)
                val ag = row.getAdGroup
                println(s"name = ${ag.getName}")
            }
            println(v.length)
        }
        // === DAC_メナード化粧品
        val adGroupId = 148913435882L
        // === 花粉連動_やや多い以上_東北_20230323-20230430
        // val adGroupId = 146722846036L
        

        // ====================== step 4
        // 用customerId和adGroupId來開關廣告群組
        // https://ads.google.com/aw/ads?campaignId=19868462058&adGroupId=148913435882&ocid=1217809181&workspaceId=0&ascid=1217809181&authuser=0&__u=8821876131&__c=6030405994
        if(false){
            val status = AdGroupStatusEnum.AdGroupStatus.ENABLED
            // val status = AdGroupStatusEnum.AdGroupStatus.PAUSED
            val adGroupService = googleAdsClient.getVersion13.createAdGroupServiceClient()
            val rName = ResourceNames.adGroup(customerId.toLong, adGroupId)
            println("rName=")
            println(rName)
            val ag = AdGroup.newBuilder()
                .setResourceName(rName)
                .setStatus(status)
                .build()
            println("ag=")
            println(ag)
            val op = AdGroupOperation.newBuilder()
                .setUpdate(ag)
                .setUpdateMask(FieldMasks.allSetFieldsOf(ag))
                .build()
            println("op=")
            println(op)
            // 可能會吐出錯誤。影片廣告無法被修改
            // MUTATE_NOT_ALLOWED
            // Mutates are not allowed for the requested resource
            // VIDEO
            if(false){
                adGroupService.mutateAdGroups {
                    MutateAdGroupsRequest.newBuilder()
                        .setCustomerId(customerId)
                        .addOperations(op)
                        .build()
                }
            }
        }

        // ====================== step 5
        // 用adGroupId取得adGroupAdId
        if(false){
            val query = s"""
                |SELECT ad_group_ad.ad.id
                |     , ad_group_ad.ad.name
                |     , ad_group_ad.status
                |FROM ad_group_ad
                |WHERE ad_group.id = ${adGroupId}
                |""".stripMargin.trim
            val googleAdsServiceClient = googleAdsClient.getVersion13.createGoogleAdsServiceClient()
            val r = googleAdsServiceClient.search(
                SearchGoogleAdsRequest.newBuilder()
                    .setQuery(query)
                    .setCustomerId(customerId)
                    .build()
            )
            val v = r.iterateAll().asScala.map { row => row }.toVector
            v.foreach { row => 
                println("===========")
                println(row)
                val aga = row.getAdGroupAd
                val ad = aga.getAd
                println(s"id = ${ad.getId}")
                println(s"name = ${ad.getName}")
            }
            println(v.length)
        }
        // === 紫外線「5」
        val adGroupAdId = 652266970697L;
        // 
        // val adGroupAdId = 650332204795L;

        // ====================== step 6
        // 用customerId和adGroupId和adGroupAdId來開關廣告
        if(false){
            //val status = AdGroupAdStatusEnum.AdGroupAdStatus.ENABLED
            val status = AdGroupAdStatusEnum.AdGroupAdStatus.PAUSED
            val adGroupAdService = googleAdsClient.getVersion13.createAdGroupAdServiceClient()
            val rName = ResourceNames.adGroupAd(customerId.toLong, adGroupId, adGroupAdId)
            val ad = AdGroupAd.newBuilder()
                .setResourceName(rName)
                .setStatus(status)
                .build()
            val op = AdGroupAdOperation.newBuilder()
                .setUpdate(ad)
                .setUpdateMask(FieldMasks.allSetFieldsOf(ad))
                .build()
            println(op)
            // 可能會吐出錯誤。影片廣告無法被修改
            // MUTATE_NOT_ALLOWED
            // Mutates are not allowed for the requested resource
            // VIDEO
            // https://developers.google.com/google-ads/api/docs/campaigns/overview?hl=zh-cn#differences_from_the_google_ads_ui
            if(false){
                adGroupAdService.mutateAdGroupAds {
                    MutateAdGroupAdsRequest.newBuilder()
                        .setCustomerId(customerId)
                        .addOperations(op)
                        .build()
                }
            }
        }
    }
}
