using System;
namespace Niba{
public struct ConfigItem {
public string ID;
public string Name;
public string Description;
public string Type;
public string SkillType;
public int MaxCount;
public string FusionRequire;
public string SkillRequire;
public string Ability;
public string Position;
public int UseCount;
public int AutoCreateCount;
public const int ID_COUNT = 30;
public const string ID_grass = "grass";
public const string ID_wood = "wood";
public const string ID_stone = "stone";
public const string ID_iron = "iron";
public const string ID_yizhi = "yizhi";
public const string ID_shepi = "shepi";
public const string ID_water = "water";
public const string ID__material_ = "_material_";
public const string ID_grassLine = "grassLine";
public const string ID_bu = "bu";
public const string ID_shepige = "shepige";
public const string ID__product_ = "_product_";
public const string ID_bengdai = "bengdai";
public const string ID_yinyongshui = "yinyongshui";
public const string ID_kaoyi = "kaoyi";
public const string ID_grassHat = "grassHat";
public const string ID_grassShoe = "grassShoe";
public const string ID_grassBody = "grassBody";
public const string ID_grassKen = "grassKen";
public const string ID__unplan_ = "_unplan_";
public const string ID_woodSword = "woodSword";
public const string ID_woodBoat = "woodBoat";
public const string ID_compass = "compass";
public const string ID_testWeapon = "testWeapon";
public const string ID_hitRing = "hitRing";
public const string ID_testBody = "testBody";
public const string ID_posion = "posion";
public const string ID_powerRing = "powerRing";
public const string ID_woodworkerBook1 = "woodworkerBook1";
public const string ID_shedan = "shedan";
public static ConfigItem Get(int key){
switch(key){
case 0: return new ConfigItem {ID="grass",Name="草",Type="material",SkillType="tailor",MaxCount=99};
case 1: return new ConfigItem {ID="wood",Name="木",Type="material",SkillType="woodworker",MaxCount=10};
case 2: return new ConfigItem {ID="stone",Name="石",Type="material",SkillType="ironworker",MaxCount=10};
case 3: return new ConfigItem {ID="iron",Name="鉄礦",Type="material",SkillType="ironworker",MaxCount=10};
case 4: return new ConfigItem {ID="yizhi",Name="蟻肢",Type="material",MaxCount=99};
case 5: return new ConfigItem {ID="shepi",Name="蛇皮",Type="material",MaxCount=10};
case 6: return new ConfigItem {ID="water",Name="水",Type="material",MaxCount=99};
case 7: return new ConfigItem {ID="_material_"};
case 8: return new ConfigItem {ID="grassLine",Name="草繩",Type="material",SkillType="tailor",MaxCount=99,FusionRequire="grass_3"};
case 9: return new ConfigItem {ID="bu",Name="布",Type="material",SkillType="tailor",MaxCount=99,FusionRequire="grass_3,wood"};
case 10: return new ConfigItem {ID="shepige",Name="蛇皮革",Type="material",SkillType="tailor",MaxCount=99,FusionRequire="shepi_3,wood"};
case 11: return new ConfigItem {ID="_product_"};
case 12: return new ConfigItem {ID="bengdai",Name="綳帶",Type="food",SkillType="tailor",MaxCount=20,FusionRequire="grassLine_2",Ability="hp_15"};
case 13: return new ConfigItem {ID="yinyongshui",Name="飲用水",Type="food",SkillType="fencingArt",MaxCount=99,FusionRequire="water_3",Ability="hp_5"};
case 14: return new ConfigItem {ID="kaoyi",Name="烤蟻",Type="food",SkillType="cooker",MaxCount=99,FusionRequire="yizhi_6,water_2",Ability="hp_30"};
case 15: return new ConfigItem {ID="grassHat",Name="草帽",Type="weapon",SkillType="speed",MaxCount=1,FusionRequire="grassLine_2,grass_10",Ability="def+2",Position="head",UseCount=20};
case 16: return new ConfigItem {ID="grassShoe",Name="草鞋",Type="weapon",SkillType="speed",MaxCount=1,FusionRequire="grassLine_3,grass_10",Ability="def+2",Position="foot",UseCount=20};
case 17: return new ConfigItem {ID="grassBody",Name="草衣",Type="weapon",SkillType="speed",MaxCount=1,FusionRequire="grassLine_5,grass_30",SkillRequire="tailor_1",Ability="def+4",Position="body",UseCount=20};
case 18: return new ConfigItem {ID="grassKen",Name="布拳套",Type="weapon",SkillType="karate",MaxCount=1,FusionRequire="bu_2,grassLine_2",SkillRequire="tailor_1",Ability="atk+2",Position="hand",UseCount=20};
case 19: return new ConfigItem {ID="_unplan_"};
case 20: return new ConfigItem {ID="woodSword",Name="木劍",Type="weapon",SkillType="fencingArt",MaxCount=1,FusionRequire="wood_5",SkillRequire="woodworker_1",Ability="atk+5",Position="hand",UseCount=40};
case 21: return new ConfigItem {ID="woodBoat",Name="木伐",Description="可以通過淺海",Type="material",SkillType="woodworker",MaxCount=1,FusionRequire="wood_10",SkillRequire="woodworker_1"};
case 22: return new ConfigItem {ID="compass",Name="羅盤",Description="通過深海的必要道具",Type="material",SkillType="ironworker",MaxCount=1,FusionRequire="iron,stone",SkillRequire="woodworker_1"};
case 23: return new ConfigItem {ID="testWeapon",Name="測試武器",Type="weapon",SkillType="fencingArt",MaxCount=1,Ability="atk+100",Position="hand"};
case 24: return new ConfigItem {ID="hitRing",Name="命中指環",Type="weapon",SkillType="subtle",MaxCount=1,Ability="accuracy+100",Position="accessory"};
case 25: return new ConfigItem {ID="testBody",Name="測試防具",Type="weapon",SkillType="armor",MaxCount=1,Ability="def+100",Position="body"};
case 26: return new ConfigItem {ID="posion",Name="補血藥",Type="food",MaxCount=10};
case 27: return new ConfigItem {ID="powerRing",Name="力量戒指",Type="weapon",SkillType="subtle",MaxCount=1,Ability="str+30",Position="accessory"};
case 28: return new ConfigItem {ID="woodworkerBook1",Name="木工1",Type="important",MaxCount=1,Ability="woodworker+1"};
case 29: return new ConfigItem {ID="shedan",Name="蛇膽",Type="food",MaxCount=5};
default: throw new Exception(key+"");
}}public static ConfigItem Get(string key){
switch(key){
case "grass": return new ConfigItem {ID="grass",Name="草",Type="material",SkillType="tailor",MaxCount=99};
case "wood": return new ConfigItem {ID="wood",Name="木",Type="material",SkillType="woodworker",MaxCount=10};
case "stone": return new ConfigItem {ID="stone",Name="石",Type="material",SkillType="ironworker",MaxCount=10};
case "iron": return new ConfigItem {ID="iron",Name="鉄礦",Type="material",SkillType="ironworker",MaxCount=10};
case "yizhi": return new ConfigItem {ID="yizhi",Name="蟻肢",Type="material",MaxCount=99};
case "shepi": return new ConfigItem {ID="shepi",Name="蛇皮",Type="material",MaxCount=10};
case "water": return new ConfigItem {ID="water",Name="水",Type="material",MaxCount=99};
case "_material_": return new ConfigItem {ID="_material_"};
case "grassLine": return new ConfigItem {ID="grassLine",Name="草繩",Type="material",SkillType="tailor",MaxCount=99,FusionRequire="grass_3"};
case "bu": return new ConfigItem {ID="bu",Name="布",Type="material",SkillType="tailor",MaxCount=99,FusionRequire="grass_3,wood"};
case "shepige": return new ConfigItem {ID="shepige",Name="蛇皮革",Type="material",SkillType="tailor",MaxCount=99,FusionRequire="shepi_3,wood"};
case "_product_": return new ConfigItem {ID="_product_"};
case "bengdai": return new ConfigItem {ID="bengdai",Name="綳帶",Type="food",SkillType="tailor",MaxCount=20,FusionRequire="grassLine_2",Ability="hp_15"};
case "yinyongshui": return new ConfigItem {ID="yinyongshui",Name="飲用水",Type="food",SkillType="fencingArt",MaxCount=99,FusionRequire="water_3",Ability="hp_5"};
case "kaoyi": return new ConfigItem {ID="kaoyi",Name="烤蟻",Type="food",SkillType="cooker",MaxCount=99,FusionRequire="yizhi_6,water_2",Ability="hp_30"};
case "grassHat": return new ConfigItem {ID="grassHat",Name="草帽",Type="weapon",SkillType="speed",MaxCount=1,FusionRequire="grassLine_2,grass_10",Ability="def+2",Position="head",UseCount=20};
case "grassShoe": return new ConfigItem {ID="grassShoe",Name="草鞋",Type="weapon",SkillType="speed",MaxCount=1,FusionRequire="grassLine_3,grass_10",Ability="def+2",Position="foot",UseCount=20};
case "grassBody": return new ConfigItem {ID="grassBody",Name="草衣",Type="weapon",SkillType="speed",MaxCount=1,FusionRequire="grassLine_5,grass_30",SkillRequire="tailor_1",Ability="def+4",Position="body",UseCount=20};
case "grassKen": return new ConfigItem {ID="grassKen",Name="布拳套",Type="weapon",SkillType="karate",MaxCount=1,FusionRequire="bu_2,grassLine_2",SkillRequire="tailor_1",Ability="atk+2",Position="hand",UseCount=20};
case "_unplan_": return new ConfigItem {ID="_unplan_"};
case "woodSword": return new ConfigItem {ID="woodSword",Name="木劍",Type="weapon",SkillType="fencingArt",MaxCount=1,FusionRequire="wood_5",SkillRequire="woodworker_1",Ability="atk+5",Position="hand",UseCount=40};
case "woodBoat": return new ConfigItem {ID="woodBoat",Name="木伐",Description="可以通過淺海",Type="material",SkillType="woodworker",MaxCount=1,FusionRequire="wood_10",SkillRequire="woodworker_1"};
case "compass": return new ConfigItem {ID="compass",Name="羅盤",Description="通過深海的必要道具",Type="material",SkillType="ironworker",MaxCount=1,FusionRequire="iron,stone",SkillRequire="woodworker_1"};
case "testWeapon": return new ConfigItem {ID="testWeapon",Name="測試武器",Type="weapon",SkillType="fencingArt",MaxCount=1,Ability="atk+100",Position="hand"};
case "hitRing": return new ConfigItem {ID="hitRing",Name="命中指環",Type="weapon",SkillType="subtle",MaxCount=1,Ability="accuracy+100",Position="accessory"};
case "testBody": return new ConfigItem {ID="testBody",Name="測試防具",Type="weapon",SkillType="armor",MaxCount=1,Ability="def+100",Position="body"};
case "posion": return new ConfigItem {ID="posion",Name="補血藥",Type="food",MaxCount=10};
case "powerRing": return new ConfigItem {ID="powerRing",Name="力量戒指",Type="weapon",SkillType="subtle",MaxCount=1,Ability="str+30",Position="accessory"};
case "woodworkerBook1": return new ConfigItem {ID="woodworkerBook1",Name="木工1",Type="important",MaxCount=1,Ability="woodworker+1"};
case "shedan": return new ConfigItem {ID="shedan",Name="蛇膽",Type="food",MaxCount=5};
default: throw new Exception(key);
}}}}