// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package desktop

// MergeStringCardStack is
func MergeStringCardStack(a map[string]CardStack, b map[string]CardStack) map[string]CardStack {
	ret := map[string]CardStack{}
	for k, v := range a {
		ret[k] = v
	}
	for k, v := range b {
		ret[k] = v
	}
	return ret
}

// AssocStringCardStack is
func AssocStringCardStack(a map[string]CardStack, k string, v CardStack) map[string]CardStack {
	ret := map[string]CardStack{}
	for k, v := range a {
		ret[k] = v
	}
	ret[k] = v
	return ret
}
