// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package protocol

import (
	"fmt"
	"math/rand"
	"time"
)

// ShufflePosition is
func ShufflePosition(arr []Position) {
	t := time.Now()
	rand.Seed(int64(t.Nanosecond()))

	for i := len(arr) - 1; i > 0; i-- {
		j := rand.Intn(i)
		arr[i], arr[j] = arr[j], arr[i]
	}
}

// FilterPosition is
func FilterPosition(s1 []Position, f func(Position) bool) []Position {
	ret := []Position{}
	for _, v := range s1 {
		if f(v) {
			ret = append(ret, v)
		}
	}
	return ret
}

// RemovePosition is
func RemovePosition(s1 []Position, card Position) ([]Position, error) {
	if len(s1) == 0 {
		return s1, nil
	}
	ret := []Position{}
	for _, c := range s1 {
		if c == card {
			continue
		}
		ret = append(ret, c)
	}
	if len(s1) == len(ret) {
		return s1, fmt.Errorf("item not found")
	}
	return ret, nil
}

// ReplacePosition is
func ReplacePosition(items []Position, info map[Position]Position) []Position {
	ret := make([]Position, len(items))
	copy(ret, items)
	for origin, next := range info {
		for idx, card := range items {
			if card == origin {
				ret[idx] = next
			}
		}
	}
	return ret
}

// FindPositionIndex is
func FindPositionIndex(items []Position, target Position) int {
	for idx, item := range items {
		if item == target {
			return idx
		}
	}
	return -1
}

// ReplacePositionIndex is
func ReplacePositionIndex(items []Position, info map[int]Position) []Position {
	ret := make([]Position, len(items))
	copy(ret, items)
	for idx2, next := range info {
		for idx := range items {
			if idx == idx2 {
				ret[idx] = next
			}
		}
	}
	return ret
}

// TryGetPosition
func TryGetPosition(items []Position, i int) (Position, error) {
	if i < 0 || i >= len(items) {
		ret := map[int]Position{}
		return ret[0], fmt.Errorf("[TryGetPosition]out of range (%v/%v)", i, len(items))
	}
	return items[i], nil
}

// TryGetPosition2
func TryGetPosition2(items [][]Position, i int) func(j int, err error) (Position, error) {
	return func(j int, err error) (Position, error) {
		if err != nil {
			ret := map[int]Position{}
			return ret[0], err
		}
		if i < 0 || i >= len(items) {
			ret := map[int]Position{}
			return ret[0], fmt.Errorf("[TryGetPosition2]out of range i (%v/%v)", i, len(items))
		}
		if j < 0 || j >= len(items[i]) {
			ret := map[int]Position{}
			return ret[0], fmt.Errorf("[TryGetPosition2]out of range j (%v/%v)", j, len(items[i]))
		}
		return items[i][j], nil
	}
}

// DifferencePosition
func DifferencePosition(a []Position, b []Position) []Position {
	ret := []Position{}
	for _, v := range a {
		has := false
		for _, v2 := range b {
			if v == v2 {
				has = true
				break
			}
		}
		if has == false {
			ret = append(ret, v)
		}
	}
	return ret
}

// IntersectionPosition
func IntersectionPosition(a []Position, b []Position) []Position {
	ret := []Position{}
	for _, v := range a {
		for _, v2 := range b {
			if v == v2 {
				ret = append(ret, v)
			}
		}
	}
	return ret
}
