// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package tool

import (
	"fmt"
	"math/rand"
	"time"
)

// ShuffleInt is
func ShuffleInt(arr []int) {
	t := time.Now()
	rand.Seed(int64(t.Nanosecond()))

	for i := len(arr) - 1; i > 0; i-- {
		j := rand.Intn(i)
		arr[i], arr[j] = arr[j], arr[i]
	}
}

// FilterInt is
func FilterInt(s1 []int, f func(int) bool) []int {
	ret := []int{}
	for _, v := range s1 {
		if f(v) {
			ret = append(ret, v)
		}
	}
	return ret
}

// RemoveInt is
func RemoveInt(s1 []int, card int) ([]int, error) {
	if len(s1) == 0 {
		return s1, nil
	}
	ret := []int{}
	for _, c := range s1 {
		if c == card {
			continue
		}
		ret = append(ret, c)
	}
	if len(s1) == len(ret) {
		return s1, fmt.Errorf("item not found")
	}
	return ret, nil
}

// ReplaceInt is
func ReplaceInt(items []int, info map[int]int) []int {
	ret := make([]int, len(items))
	copy(ret, items)
	for origin, next := range info {
		for idx, card := range items {
			if card == origin {
				ret[idx] = next
			}
		}
	}
	return ret
}

// ReplaceIndex is
func ReplaceIndex(items []int, info map[int]int) []int {
	ret := make([]int, len(items))
	copy(ret, items)
	for idx2, next := range info {
		for idx := range items {
			if idx == idx2 {
				ret[idx] = next
			}
		}
	}
	return ret
}
