// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package data

// KesStringRobotProto is
func KesStringRobotProto(dict map[string]RobotProto) []string {
	ret := make([]string, 0, len(dict))
	for k := range dict {
		ret = append(ret, k)
	}
	return ret
}

// ValsStringRobotProto is
func ValsStringRobotProto(dict map[string]RobotProto) []RobotProto {
	ret := make([]RobotProto, 0, len(dict))
	for _, v := range dict {
		ret = append(ret, v)
	}
	return ret
}

// MergeStringRobotProto is
func MergeStringRobotProto(a map[string]RobotProto, b map[string]RobotProto) map[string]RobotProto {
	ret := map[string]RobotProto{}
	for k, v := range a {
		ret[k] = v
	}
	for k, v := range b {
		ret[k] = v
	}
	return ret
}

// AssocStringRobotProto is
func AssocStringRobotProto(a map[string]RobotProto, k string, v RobotProto) map[string]RobotProto {
	ret := map[string]RobotProto{}
	for k, v := range a {
		ret[k] = v
	}
	ret[k] = v
	return ret
}

// DissocStringRobotProto is
func DissocStringRobotProto(a map[string]RobotProto, k string) map[string]RobotProto {
	ret := map[string]RobotProto{}
	for k, v := range a {
		ret[k] = v
	}
	delete(ret, k)
	return ret
}
