// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package data

// KesStringPilotProto is
func KesStringPilotProto(dict map[string]PilotProto) []string {
	ret := make([]string, 0, len(dict))
	for k := range dict {
		ret = append(ret, k)
	}
	return ret
}

// ValsStringPilotProto is
func ValsStringPilotProto(dict map[string]PilotProto) []PilotProto {
	ret := make([]PilotProto, 0, len(dict))
	for _, v := range dict {
		ret = append(ret, v)
	}
	return ret
}

// MergeStringPilotProto is
func MergeStringPilotProto(a map[string]PilotProto, b map[string]PilotProto) map[string]PilotProto {
	ret := map[string]PilotProto{}
	for k, v := range a {
		ret[k] = v
	}
	for k, v := range b {
		ret[k] = v
	}
	return ret
}

// AssocStringPilotProto is
func AssocStringPilotProto(a map[string]PilotProto, k string, v PilotProto) map[string]PilotProto {
	ret := map[string]PilotProto{}
	for k, v := range a {
		ret[k] = v
	}
	ret[k] = v
	return ret
}

// DissocStringPilotProto is
func DissocStringPilotProto(a map[string]PilotProto, k string) map[string]PilotProto {
	ret := map[string]PilotProto{}
	for k, v := range a {
		ret[k] = v
	}
	delete(ret, k)
	return ret
}
