// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package data

// KesStringTag is
func KesStringTag(dict map[string]Tag) []string {
	ret := make([]string, 0, len(dict))
	for k := range dict {
		ret = append(ret, k)
	}
	return ret
}

// ValsStringTag is
func ValsStringTag(dict map[string]Tag) []Tag {
	ret := make([]Tag, 0, len(dict))
	for _, v := range dict {
		ret = append(ret, v)
	}
	return ret
}

// MergeStringTag is
func MergeStringTag(a map[string]Tag, b map[string]Tag) map[string]Tag {
	ret := map[string]Tag{}
	for k, v := range a {
		ret[k] = v
	}
	for k, v := range b {
		ret[k] = v
	}
	return ret
}

// AssocStringTag is
func AssocStringTag(a map[string]Tag, k string, v Tag) map[string]Tag {
	ret := map[string]Tag{}
	for k, v := range a {
		ret[k] = v
	}
	ret[k] = v
	return ret
}

// DissocStringTag is
func DissocStringTag(a map[string]Tag, k string) map[string]Tag {
	ret := map[string]Tag{}
	for k, v := range a {
		ret[k] = v
	}
	delete(ret, k)
	return ret
}
