// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package data

// KesStringString is
func KesStringString(dict map[string]string) []string {
	ret := make([]string, 0, len(dict))
	for k := range dict {
		ret = append(ret, k)
	}
	return ret
}

// ValsStringString is
func ValsStringString(dict map[string]string) []string {
	ret := make([]string, 0, len(dict))
	for _, v := range dict {
		ret = append(ret, v)
	}
	return ret
}

// MergeStringString is
func MergeStringString(a map[string]string, b map[string]string) map[string]string {
	ret := map[string]string{}
	for k, v := range a {
		ret[k] = v
	}
	for k, v := range b {
		ret[k] = v
	}
	return ret
}

// AssocStringString is
func AssocStringString(a map[string]string, k string, v string) map[string]string {
	ret := map[string]string{}
	for k, v := range a {
		ret[k] = v
	}
	ret[k] = v
	return ret
}

// DissocStringString is
func DissocStringString(a map[string]string, k string) map[string]string {
	ret := map[string]string{}
	for k, v := range a {
		ret[k] = v
	}
	delete(ret, k)
	return ret
}
