import type { MapTemplate } from './mapTemplates'

/**
 * 挑戰關卡第一輪（v1）：20 個由簡單到極度困難的沙盒開局模版。
 *
 * 取值遵循 handev/difficulty-metrics-guide.md：
 * - 加難度軸線：巢穴數、初始怪數遞增；第 16 關起改為雙城防守（A1 多線壓力）；地形權重逐步轉惡。
 * - 減難度軸線：資源點、廢墟、武館遞減，收緊經濟與成長曲線。
 * - 福利度軸線：道具點只增不減（難度 − 福利 ≈ 恆定），高難關靠大量免費掉寶撐住勝利期盼。
 * - 探索事件全數關閉（eventCount 0）：挑戰系列講求確定性，排除隨機變數。
 */
export const CHALLENGE_TEMPLATES_V1: MapTemplate[] = [
  {
    id: 'challenge-v1-01',
    name: '挑戰I·01 初入江湖',
    builtin: true,
    settings: {
      rows: 15,
      columns: 15,
      baseCount: 1,
      nestCount: 1,
      resourcePointCount: 5,
      itemPointCount: 4,
      playerCount: 1,
      aiPlayerCount: 0,
      explorationEventCount: 0,
      explorationTriggerChance: 0,
      creatureCount: 0,
      ruinCount: 12,
      sectGateCount: 3,
      terrainWeights: { plain: 70, forest: 8, water: 6, mountain: 6, desert: 10 },
    },
  },
  {
    id: 'challenge-v1-02',
    name: '挑戰I·02 初露鋒芒',
    builtin: true,
    settings: {
      rows: 15,
      columns: 15,
      baseCount: 1,
      nestCount: 1,
      resourcePointCount: 5,
      itemPointCount: 5,
      playerCount: 1,
      aiPlayerCount: 0,
      explorationEventCount: 0,
      explorationTriggerChance: 0,
      creatureCount: 1,
      ruinCount: 11,
      sectGateCount: 3,
      terrainWeights: { plain: 70, forest: 8, water: 6, mountain: 6, desert: 10 },
    },
  },
  {
    id: 'challenge-v1-03',
    name: '挑戰I·03 略有小成',
    builtin: true,
    settings: {
      rows: 16,
      columns: 16,
      baseCount: 1,
      nestCount: 2,
      resourcePointCount: 5,
      itemPointCount: 6,
      playerCount: 1,
      aiPlayerCount: 0,
      explorationEventCount: 0,
      explorationTriggerChance: 0,
      creatureCount: 2,
      ruinCount: 10,
      sectGateCount: 3,
      terrainWeights: { plain: 40, forest: 20, water: 10, mountain: 15, desert: 15 },
    },
  },
  {
    id: 'challenge-v1-04',
    name: '挑戰I·04 駕輕就熟',
    builtin: true,
    settings: {
      rows: 16,
      columns: 16,
      baseCount: 1,
      nestCount: 2,
      resourcePointCount: 4,
      itemPointCount: 7,
      playerCount: 1,
      aiPlayerCount: 0,
      explorationEventCount: 0,
      explorationTriggerChance: 0,
      creatureCount: 3,
      ruinCount: 10,
      sectGateCount: 2,
      terrainWeights: { plain: 40, forest: 20, water: 10, mountain: 15, desert: 15 },
    },
  },
  {
    id: 'challenge-v1-05',
    name: '挑戰I·05 融會貫通',
    builtin: true,
    settings: {
      rows: 18,
      columns: 18,
      baseCount: 1,
      nestCount: 2,
      resourcePointCount: 4,
      itemPointCount: 9,
      playerCount: 1,
      aiPlayerCount: 0,
      explorationEventCount: 0,
      explorationTriggerChance: 0,
      creatureCount: 4,
      ruinCount: 9,
      sectGateCount: 2,
      terrainWeights: { plain: 40, forest: 20, water: 10, mountain: 15, desert: 15 },
    },
  },
  {
    id: 'challenge-v1-06',
    name: '挑戰I·06 名動一方',
    builtin: true,
    settings: {
      rows: 18,
      columns: 18,
      baseCount: 1,
      nestCount: 3,
      resourcePointCount: 4,
      itemPointCount: 11,
      playerCount: 1,
      aiPlayerCount: 0,
      explorationEventCount: 0,
      explorationTriggerChance: 0,
      creatureCount: 5,
      ruinCount: 8,
      sectGateCount: 2,
      terrainWeights: { plain: 30, forest: 48, water: 8, mountain: 9, desert: 5 },
    },
  },
  {
    id: 'challenge-v1-07',
    name: '挑戰I·07 風起雲湧',
    builtin: true,
    settings: {
      rows: 18,
      columns: 18,
      baseCount: 1,
      nestCount: 3,
      resourcePointCount: 4,
      itemPointCount: 13,
      playerCount: 1,
      aiPlayerCount: 0,
      explorationEventCount: 0,
      explorationTriggerChance: 0,
      creatureCount: 6,
      ruinCount: 8,
      sectGateCount: 2,
      terrainWeights: { plain: 40, forest: 20, water: 10, mountain: 15, desert: 15 },
    },
  },
  {
    id: 'challenge-v1-08',
    name: '挑戰I·08 山雨欲來',
    builtin: true,
    settings: {
      rows: 20,
      columns: 20,
      baseCount: 1,
      nestCount: 3,
      resourcePointCount: 4,
      itemPointCount: 15,
      playerCount: 1,
      aiPlayerCount: 0,
      explorationEventCount: 0,
      explorationTriggerChance: 0,
      creatureCount: 7,
      ruinCount: 7,
      sectGateCount: 1,
      terrainWeights: { plain: 32, forest: 5, water: 5, mountain: 13, desert: 45 },
    },
  },
  {
    id: 'challenge-v1-09',
    name: '挑戰I·09 危機四伏',
    builtin: true,
    settings: {
      rows: 20,
      columns: 20,
      baseCount: 1,
      nestCount: 4,
      resourcePointCount: 4,
      itemPointCount: 17,
      playerCount: 1,
      aiPlayerCount: 0,
      explorationEventCount: 0,
      explorationTriggerChance: 0,
      creatureCount: 8,
      ruinCount: 7,
      sectGateCount: 1,
      terrainWeights: { plain: 40, forest: 20, water: 10, mountain: 15, desert: 15 },
    },
  },
  {
    id: 'challenge-v1-10',
    name: '挑戰I·10 十面埋伏',
    builtin: true,
    settings: {
      rows: 20,
      columns: 20,
      baseCount: 1,
      nestCount: 4,
      resourcePointCount: 3,
      itemPointCount: 19,
      playerCount: 1,
      aiPlayerCount: 0,
      explorationEventCount: 0,
      explorationTriggerChance: 0,
      creatureCount: 9,
      ruinCount: 6,
      sectGateCount: 1,
      terrainWeights: { plain: 32, forest: 14, water: 7, mountain: 42, desert: 5 },
    },
  },
  {
    id: 'challenge-v1-11',
    name: '挑戰I·11 險象環生',
    builtin: true,
    settings: {
      rows: 22,
      columns: 22,
      baseCount: 1,
      nestCount: 4,
      resourcePointCount: 3,
      itemPointCount: 21,
      playerCount: 1,
      aiPlayerCount: 0,
      explorationEventCount: 0,
      explorationTriggerChance: 0,
      creatureCount: 10,
      ruinCount: 6,
      sectGateCount: 1,
      terrainWeights: { plain: 36, forest: 12, water: 40, mountain: 7, desert: 5 },
    },
  },
  {
    id: 'challenge-v1-12',
    name: '挑戰I·12 命懸一線',
    builtin: true,
    settings: {
      rows: 22,
      columns: 22,
      baseCount: 1,
      nestCount: 5,
      resourcePointCount: 3,
      itemPointCount: 23,
      playerCount: 1,
      aiPlayerCount: 0,
      explorationEventCount: 0,
      explorationTriggerChance: 0,
      creatureCount: 11,
      ruinCount: 5,
      sectGateCount: 1,
      terrainWeights: { plain: 30, forest: 48, water: 8, mountain: 9, desert: 5 },
    },
  },
  {
    id: 'challenge-v1-13',
    name: '挑戰I·13 九死一生',
    builtin: true,
    settings: {
      rows: 24,
      columns: 24,
      baseCount: 1,
      nestCount: 5,
      resourcePointCount: 3,
      itemPointCount: 25,
      playerCount: 1,
      aiPlayerCount: 0,
      explorationEventCount: 0,
      explorationTriggerChance: 0,
      creatureCount: 12,
      ruinCount: 5,
      sectGateCount: 0,
      terrainWeights: { plain: 32, forest: 14, water: 7, mountain: 42, desert: 5 },
    },
  },
  {
    id: 'challenge-v1-14',
    name: '挑戰I·14 絕境逢生',
    builtin: true,
    settings: {
      rows: 24,
      columns: 24,
      baseCount: 1,
      nestCount: 5,
      resourcePointCount: 3,
      itemPointCount: 27,
      playerCount: 1,
      aiPlayerCount: 0,
      explorationEventCount: 0,
      explorationTriggerChance: 0,
      creatureCount: 14,
      ruinCount: 4,
      sectGateCount: 0,
      terrainWeights: { plain: 32, forest: 5, water: 5, mountain: 13, desert: 45 },
    },
  },
  {
    id: 'challenge-v1-15',
    name: '挑戰I·15 天羅地網',
    builtin: true,
    settings: {
      rows: 26,
      columns: 26,
      baseCount: 1,
      nestCount: 6,
      resourcePointCount: 3,
      itemPointCount: 29,
      playerCount: 1,
      aiPlayerCount: 0,
      explorationEventCount: 0,
      explorationTriggerChance: 0,
      creatureCount: 16,
      ruinCount: 4,
      sectGateCount: 0,
      terrainWeights: { plain: 36, forest: 12, water: 40, mountain: 7, desert: 5 },
    },
  },
  {
    id: 'challenge-v1-16',
    name: '挑戰I·16 內憂外患',
    builtin: true,
    settings: {
      rows: 26,
      columns: 26,
      baseCount: 2,
      nestCount: 6,
      resourcePointCount: 3,
      itemPointCount: 32,
      playerCount: 1,
      aiPlayerCount: 0,
      explorationEventCount: 0,
      explorationTriggerChance: 0,
      creatureCount: 18,
      ruinCount: 3,
      sectGateCount: 0,
      terrainWeights: { plain: 26, forest: 22, water: 16, mountain: 20, desert: 16 },
    },
  },
  {
    id: 'challenge-v1-17',
    name: '挑戰I·17 兵臨城下',
    builtin: true,
    settings: {
      rows: 28,
      columns: 28,
      baseCount: 2,
      nestCount: 7,
      resourcePointCount: 3,
      itemPointCount: 35,
      playerCount: 1,
      aiPlayerCount: 0,
      explorationEventCount: 0,
      explorationTriggerChance: 0,
      creatureCount: 20,
      ruinCount: 3,
      sectGateCount: 0,
      terrainWeights: { plain: 26, forest: 22, water: 16, mountain: 20, desert: 16 },
    },
  },
  {
    id: 'challenge-v1-18',
    name: '挑戰I·18 存亡之秋',
    builtin: true,
    settings: {
      rows: 30,
      columns: 30,
      baseCount: 2,
      nestCount: 7,
      resourcePointCount: 3,
      itemPointCount: 39,
      playerCount: 1,
      aiPlayerCount: 0,
      explorationEventCount: 0,
      explorationTriggerChance: 0,
      creatureCount: 23,
      ruinCount: 2,
      sectGateCount: 0,
      terrainWeights: { plain: 26, forest: 22, water: 16, mountain: 20, desert: 16 },
    },
  },
  {
    id: 'challenge-v1-19',
    name: '挑戰I·19 萬劫不復',
    builtin: true,
    settings: {
      rows: 32,
      columns: 32,
      baseCount: 2,
      nestCount: 8,
      resourcePointCount: 2,
      itemPointCount: 42,
      playerCount: 1,
      aiPlayerCount: 0,
      explorationEventCount: 0,
      explorationTriggerChance: 0,
      creatureCount: 26,
      ruinCount: 2,
      sectGateCount: 0,
      terrainWeights: { plain: 26, forest: 22, water: 16, mountain: 20, desert: 16 },
    },
  },
  {
    id: 'challenge-v1-20',
    name: '挑戰I·20 無間煉獄',
    builtin: true,
    settings: {
      rows: 34,
      columns: 34,
      baseCount: 2,
      nestCount: 9,
      resourcePointCount: 2,
      itemPointCount: 46,
      playerCount: 1,
      aiPlayerCount: 0,
      explorationEventCount: 0,
      explorationTriggerChance: 0,
      creatureCount: 30,
      ruinCount: 1,
      sectGateCount: 0,
      terrainWeights: { plain: 26, forest: 22, water: 16, mountain: 20, desert: 16 },
    },
  },
]
