import type { MapTemplate } from './mapTemplates'

/**
 * 挑戰關卡系列：由簡單到極度困難的沙盒開局模版，各輪 20 關。
 *
 * 取值遵循 handev/difficulty-metrics-guide.md：
 * - 加難度軸線：巢穴數、初始怪數、防守城數遞增；地形權重逐步轉惡。
 *   v1 以單城為主、第 16 關起雙城（終點 2 城/9 巢）；
 *   v2 以多線防守為主軸——1 城(01-07)→2 城(08-12)→3 城(13-16)→4 城(17-19)→5 城(20)，終點 5 城/15 巢。
 * - 資源點非難度參數：嚴守「每城 3 點」比例（resourcePointCount = 3 × baseCount），僅靠位置調節難度。
 * - 減難度軸線：廢墟、武館遞減，收緊成長曲線。
 * - 福利度軸線：道具點只增不減（難度 − 福利 ≈ 恆定）；系列整體越難，福利曲線越高
 *   （v1 為 4→46，v2 為 6→58），高難關靠大量免費掉寶撐住勝利期盼。
 * - 探索事件全數關閉（eventCount 0）：挑戰系列講求確定性，排除隨機變數。
 */
export const CHALLENGE_TEMPLATES_V1: MapTemplate[] = [
  {
    id: 'challenge-v1-01',
    name: '挑戰I·01 初入江湖',
    builtin: true,
    settings: {
      rows: 15,
      columns: 15,
      baseCount: 1,
      nestCount: 1,
      resourcePointCount: 3,
      itemPointCount: 4,
      playerCount: 1,
      aiPlayerCount: 0,
      explorationEventCount: 0,
      explorationTriggerChance: 0,
      creatureCount: 0,
      ruinCount: 12,
      sectGateCount: 3,
      terrainWeights: { plain: 70, forest: 8, water: 6, mountain: 6, desert: 10 },
    },
  },
  {
    id: 'challenge-v1-02',
    name: '挑戰I·02 初露鋒芒',
    builtin: true,
    settings: {
      rows: 15,
      columns: 15,
      baseCount: 1,
      nestCount: 1,
      resourcePointCount: 3,
      itemPointCount: 5,
      playerCount: 1,
      aiPlayerCount: 0,
      explorationEventCount: 0,
      explorationTriggerChance: 0,
      creatureCount: 1,
      ruinCount: 11,
      sectGateCount: 3,
      terrainWeights: { plain: 70, forest: 8, water: 6, mountain: 6, desert: 10 },
    },
  },
  {
    id: 'challenge-v1-03',
    name: '挑戰I·03 略有小成',
    builtin: true,
    settings: {
      rows: 16,
      columns: 16,
      baseCount: 1,
      nestCount: 2,
      resourcePointCount: 3,
      itemPointCount: 6,
      playerCount: 1,
      aiPlayerCount: 0,
      explorationEventCount: 0,
      explorationTriggerChance: 0,
      creatureCount: 2,
      ruinCount: 10,
      sectGateCount: 3,
      terrainWeights: { plain: 40, forest: 20, water: 10, mountain: 15, desert: 15 },
    },
  },
  {
    id: 'challenge-v1-04',
    name: '挑戰I·04 駕輕就熟',
    builtin: true,
    settings: {
      rows: 16,
      columns: 16,
      baseCount: 1,
      nestCount: 2,
      resourcePointCount: 3,
      itemPointCount: 7,
      playerCount: 1,
      aiPlayerCount: 0,
      explorationEventCount: 0,
      explorationTriggerChance: 0,
      creatureCount: 3,
      ruinCount: 10,
      sectGateCount: 2,
      terrainWeights: { plain: 40, forest: 20, water: 10, mountain: 15, desert: 15 },
    },
  },
  {
    id: 'challenge-v1-05',
    name: '挑戰I·05 融會貫通',
    builtin: true,
    settings: {
      rows: 18,
      columns: 18,
      baseCount: 1,
      nestCount: 2,
      resourcePointCount: 3,
      itemPointCount: 9,
      playerCount: 1,
      aiPlayerCount: 0,
      explorationEventCount: 0,
      explorationTriggerChance: 0,
      creatureCount: 4,
      ruinCount: 9,
      sectGateCount: 2,
      terrainWeights: { plain: 40, forest: 20, water: 10, mountain: 15, desert: 15 },
    },
  },
  {
    id: 'challenge-v1-06',
    name: '挑戰I·06 名動一方',
    builtin: true,
    settings: {
      rows: 18,
      columns: 18,
      baseCount: 1,
      nestCount: 3,
      resourcePointCount: 3,
      itemPointCount: 11,
      playerCount: 1,
      aiPlayerCount: 0,
      explorationEventCount: 0,
      explorationTriggerChance: 0,
      creatureCount: 5,
      ruinCount: 8,
      sectGateCount: 2,
      terrainWeights: { plain: 30, forest: 48, water: 8, mountain: 9, desert: 5 },
    },
  },
  {
    id: 'challenge-v1-07',
    name: '挑戰I·07 風起雲湧',
    builtin: true,
    settings: {
      rows: 18,
      columns: 18,
      baseCount: 1,
      nestCount: 3,
      resourcePointCount: 3,
      itemPointCount: 13,
      playerCount: 1,
      aiPlayerCount: 0,
      explorationEventCount: 0,
      explorationTriggerChance: 0,
      creatureCount: 6,
      ruinCount: 8,
      sectGateCount: 2,
      terrainWeights: { plain: 40, forest: 20, water: 10, mountain: 15, desert: 15 },
    },
  },
  {
    id: 'challenge-v1-08',
    name: '挑戰I·08 山雨欲來',
    builtin: true,
    settings: {
      rows: 20,
      columns: 20,
      baseCount: 1,
      nestCount: 3,
      resourcePointCount: 3,
      itemPointCount: 15,
      playerCount: 1,
      aiPlayerCount: 0,
      explorationEventCount: 0,
      explorationTriggerChance: 0,
      creatureCount: 7,
      ruinCount: 7,
      sectGateCount: 1,
      terrainWeights: { plain: 32, forest: 5, water: 5, mountain: 13, desert: 45 },
    },
  },
  {
    id: 'challenge-v1-09',
    name: '挑戰I·09 危機四伏',
    builtin: true,
    settings: {
      rows: 20,
      columns: 20,
      baseCount: 1,
      nestCount: 4,
      resourcePointCount: 3,
      itemPointCount: 17,
      playerCount: 1,
      aiPlayerCount: 0,
      explorationEventCount: 0,
      explorationTriggerChance: 0,
      creatureCount: 8,
      ruinCount: 7,
      sectGateCount: 1,
      terrainWeights: { plain: 40, forest: 20, water: 10, mountain: 15, desert: 15 },
    },
  },
  {
    id: 'challenge-v1-10',
    name: '挑戰I·10 十面埋伏',
    builtin: true,
    settings: {
      rows: 20,
      columns: 20,
      baseCount: 1,
      nestCount: 4,
      resourcePointCount: 3,
      itemPointCount: 19,
      playerCount: 1,
      aiPlayerCount: 0,
      explorationEventCount: 0,
      explorationTriggerChance: 0,
      creatureCount: 9,
      ruinCount: 6,
      sectGateCount: 1,
      terrainWeights: { plain: 32, forest: 14, water: 7, mountain: 42, desert: 5 },
    },
  },
  {
    id: 'challenge-v1-11',
    name: '挑戰I·11 險象環生',
    builtin: true,
    settings: {
      rows: 22,
      columns: 22,
      baseCount: 1,
      nestCount: 4,
      resourcePointCount: 3,
      itemPointCount: 21,
      playerCount: 1,
      aiPlayerCount: 0,
      explorationEventCount: 0,
      explorationTriggerChance: 0,
      creatureCount: 10,
      ruinCount: 6,
      sectGateCount: 1,
      terrainWeights: { plain: 36, forest: 12, water: 40, mountain: 7, desert: 5 },
    },
  },
  {
    id: 'challenge-v1-12',
    name: '挑戰I·12 命懸一線',
    builtin: true,
    settings: {
      rows: 22,
      columns: 22,
      baseCount: 1,
      nestCount: 5,
      resourcePointCount: 3,
      itemPointCount: 23,
      playerCount: 1,
      aiPlayerCount: 0,
      explorationEventCount: 0,
      explorationTriggerChance: 0,
      creatureCount: 11,
      ruinCount: 5,
      sectGateCount: 1,
      terrainWeights: { plain: 30, forest: 48, water: 8, mountain: 9, desert: 5 },
    },
  },
  {
    id: 'challenge-v1-13',
    name: '挑戰I·13 九死一生',
    builtin: true,
    settings: {
      rows: 24,
      columns: 24,
      baseCount: 1,
      nestCount: 5,
      resourcePointCount: 3,
      itemPointCount: 25,
      playerCount: 1,
      aiPlayerCount: 0,
      explorationEventCount: 0,
      explorationTriggerChance: 0,
      creatureCount: 12,
      ruinCount: 5,
      sectGateCount: 0,
      terrainWeights: { plain: 32, forest: 14, water: 7, mountain: 42, desert: 5 },
    },
  },
  {
    id: 'challenge-v1-14',
    name: '挑戰I·14 絕境逢生',
    builtin: true,
    settings: {
      rows: 24,
      columns: 24,
      baseCount: 1,
      nestCount: 5,
      resourcePointCount: 3,
      itemPointCount: 27,
      playerCount: 1,
      aiPlayerCount: 0,
      explorationEventCount: 0,
      explorationTriggerChance: 0,
      creatureCount: 14,
      ruinCount: 4,
      sectGateCount: 0,
      terrainWeights: { plain: 32, forest: 5, water: 5, mountain: 13, desert: 45 },
    },
  },
  {
    id: 'challenge-v1-15',
    name: '挑戰I·15 天羅地網',
    builtin: true,
    settings: {
      rows: 26,
      columns: 26,
      baseCount: 1,
      nestCount: 6,
      resourcePointCount: 3,
      itemPointCount: 29,
      playerCount: 1,
      aiPlayerCount: 0,
      explorationEventCount: 0,
      explorationTriggerChance: 0,
      creatureCount: 16,
      ruinCount: 4,
      sectGateCount: 0,
      terrainWeights: { plain: 36, forest: 12, water: 40, mountain: 7, desert: 5 },
    },
  },
  {
    id: 'challenge-v1-16',
    name: '挑戰I·16 內憂外患',
    builtin: true,
    settings: {
      rows: 26,
      columns: 26,
      baseCount: 2,
      nestCount: 6,
      resourcePointCount: 6,
      itemPointCount: 32,
      playerCount: 1,
      aiPlayerCount: 0,
      explorationEventCount: 0,
      explorationTriggerChance: 0,
      creatureCount: 18,
      ruinCount: 3,
      sectGateCount: 0,
      terrainWeights: { plain: 26, forest: 22, water: 16, mountain: 20, desert: 16 },
    },
  },
  {
    id: 'challenge-v1-17',
    name: '挑戰I·17 兵臨城下',
    builtin: true,
    settings: {
      rows: 28,
      columns: 28,
      baseCount: 2,
      nestCount: 7,
      resourcePointCount: 6,
      itemPointCount: 35,
      playerCount: 1,
      aiPlayerCount: 0,
      explorationEventCount: 0,
      explorationTriggerChance: 0,
      creatureCount: 20,
      ruinCount: 3,
      sectGateCount: 0,
      terrainWeights: { plain: 26, forest: 22, water: 16, mountain: 20, desert: 16 },
    },
  },
  {
    id: 'challenge-v1-18',
    name: '挑戰I·18 存亡之秋',
    builtin: true,
    settings: {
      rows: 30,
      columns: 30,
      baseCount: 2,
      nestCount: 7,
      resourcePointCount: 6,
      itemPointCount: 39,
      playerCount: 1,
      aiPlayerCount: 0,
      explorationEventCount: 0,
      explorationTriggerChance: 0,
      creatureCount: 23,
      ruinCount: 2,
      sectGateCount: 0,
      terrainWeights: { plain: 26, forest: 22, water: 16, mountain: 20, desert: 16 },
    },
  },
  {
    id: 'challenge-v1-19',
    name: '挑戰I·19 萬劫不復',
    builtin: true,
    settings: {
      rows: 32,
      columns: 32,
      baseCount: 2,
      nestCount: 8,
      resourcePointCount: 6,
      itemPointCount: 42,
      playerCount: 1,
      aiPlayerCount: 0,
      explorationEventCount: 0,
      explorationTriggerChance: 0,
      creatureCount: 26,
      ruinCount: 2,
      sectGateCount: 0,
      terrainWeights: { plain: 26, forest: 22, water: 16, mountain: 20, desert: 16 },
    },
  },
  {
    id: 'challenge-v1-20',
    name: '挑戰I·20 無間煉獄',
    builtin: true,
    settings: {
      rows: 34,
      columns: 34,
      baseCount: 2,
      nestCount: 9,
      resourcePointCount: 6,
      itemPointCount: 46,
      playerCount: 1,
      aiPlayerCount: 0,
      explorationEventCount: 0,
      explorationTriggerChance: 0,
      creatureCount: 30,
      ruinCount: 1,
      sectGateCount: 0,
      terrainWeights: { plain: 26, forest: 22, water: 16, mountain: 20, desert: 16 },
    },
  },
]

/** 挑戰關卡第二輪（v2）：多線防守主軸，終點 5 城/15 巢。 */
export const CHALLENGE_TEMPLATES_V2: MapTemplate[] = [
  {
    id: 'challenge-v2-01',
    name: '挑戰II·01 重整旗鼓',
    builtin: true,
    settings: {
      rows: 16,
      columns: 16,
      baseCount: 1,
      nestCount: 2,
      resourcePointCount: 3,
      itemPointCount: 6,
      playerCount: 1,
      aiPlayerCount: 0,
      explorationEventCount: 0,
      explorationTriggerChance: 0,
      creatureCount: 4,
      ruinCount: 10,
      sectGateCount: 3,
      terrainWeights: { plain: 55, forest: 15, water: 10, mountain: 10, desert: 10 },
    },
  },
  {
    id: 'challenge-v2-02',
    name: '挑戰II·02 再戰江湖',
    builtin: true,
    settings: {
      rows: 16,
      columns: 16,
      baseCount: 1,
      nestCount: 2,
      resourcePointCount: 3,
      itemPointCount: 8,
      playerCount: 1,
      aiPlayerCount: 0,
      explorationEventCount: 0,
      explorationTriggerChance: 0,
      creatureCount: 5,
      ruinCount: 10,
      sectGateCount: 3,
      terrainWeights: { plain: 55, forest: 15, water: 10, mountain: 10, desert: 10 },
    },
  },
  {
    id: 'challenge-v2-03',
    name: '挑戰II·03 群狼環伺',
    builtin: true,
    settings: {
      rows: 18,
      columns: 18,
      baseCount: 1,
      nestCount: 3,
      resourcePointCount: 3,
      itemPointCount: 10,
      playerCount: 1,
      aiPlayerCount: 0,
      explorationEventCount: 0,
      explorationTriggerChance: 0,
      creatureCount: 6,
      ruinCount: 9,
      sectGateCount: 2,
      terrainWeights: { plain: 40, forest: 20, water: 10, mountain: 15, desert: 15 },
    },
  },
  {
    id: 'challenge-v2-04',
    name: '挑戰II·04 暗流湧動',
    builtin: true,
    settings: {
      rows: 18,
      columns: 18,
      baseCount: 1,
      nestCount: 3,
      resourcePointCount: 3,
      itemPointCount: 12,
      playerCount: 1,
      aiPlayerCount: 0,
      explorationEventCount: 0,
      explorationTriggerChance: 0,
      creatureCount: 8,
      ruinCount: 9,
      sectGateCount: 2,
      terrainWeights: { plain: 40, forest: 20, water: 10, mountain: 15, desert: 15 },
    },
  },
  {
    id: 'challenge-v2-05',
    name: '挑戰II·05 烽火連天',
    builtin: true,
    settings: {
      rows: 20,
      columns: 20,
      baseCount: 1,
      nestCount: 3,
      resourcePointCount: 3,
      itemPointCount: 14,
      playerCount: 1,
      aiPlayerCount: 0,
      explorationEventCount: 0,
      explorationTriggerChance: 0,
      creatureCount: 9,
      ruinCount: 8,
      sectGateCount: 2,
      terrainWeights: { plain: 30, forest: 48, water: 8, mountain: 9, desert: 5 },
    },
  },
  {
    id: 'challenge-v2-06',
    name: '挑戰II·06 左支右絀',
    builtin: true,
    settings: {
      rows: 20,
      columns: 20,
      baseCount: 1,
      nestCount: 4,
      resourcePointCount: 3,
      itemPointCount: 16,
      playerCount: 1,
      aiPlayerCount: 0,
      explorationEventCount: 0,
      explorationTriggerChance: 0,
      creatureCount: 10,
      ruinCount: 8,
      sectGateCount: 2,
      terrainWeights: { plain: 32, forest: 5, water: 5, mountain: 13, desert: 45 },
    },
  },
  {
    id: 'challenge-v2-07',
    name: '挑戰II·07 首尾難顧',
    builtin: true,
    settings: {
      rows: 20,
      columns: 20,
      baseCount: 1,
      nestCount: 4,
      resourcePointCount: 3,
      itemPointCount: 18,
      playerCount: 1,
      aiPlayerCount: 0,
      explorationEventCount: 0,
      explorationTriggerChance: 0,
      creatureCount: 11,
      ruinCount: 8,
      sectGateCount: 2,
      terrainWeights: { plain: 32, forest: 14, water: 7, mountain: 42, desert: 5 },
    },
  },
  {
    id: 'challenge-v2-08',
    name: '挑戰II·08 分兵把守',
    builtin: true,
    settings: {
      rows: 22,
      columns: 22,
      baseCount: 2,
      nestCount: 4,
      resourcePointCount: 6,
      itemPointCount: 21,
      playerCount: 1,
      aiPlayerCount: 0,
      explorationEventCount: 0,
      explorationTriggerChance: 0,
      creatureCount: 12,
      ruinCount: 7,
      sectGateCount: 1,
      terrainWeights: { plain: 40, forest: 20, water: 10, mountain: 15, desert: 15 },
    },
  },
  {
    id: 'challenge-v2-09',
    name: '挑戰II·09 顧此失彼',
    builtin: true,
    settings: {
      rows: 22,
      columns: 22,
      baseCount: 2,
      nestCount: 5,
      resourcePointCount: 6,
      itemPointCount: 24,
      playerCount: 1,
      aiPlayerCount: 0,
      explorationEventCount: 0,
      explorationTriggerChance: 0,
      creatureCount: 13,
      ruinCount: 7,
      sectGateCount: 1,
      terrainWeights: { plain: 36, forest: 12, water: 40, mountain: 7, desert: 5 },
    },
  },
  {
    id: 'challenge-v2-10',
    name: '挑戰II·10 多線告急',
    builtin: true,
    settings: {
      rows: 22,
      columns: 22,
      baseCount: 2,
      nestCount: 5,
      resourcePointCount: 6,
      itemPointCount: 27,
      playerCount: 1,
      aiPlayerCount: 0,
      explorationEventCount: 0,
      explorationTriggerChance: 0,
      creatureCount: 14,
      ruinCount: 6,
      sectGateCount: 1,
      terrainWeights: { plain: 30, forest: 48, water: 8, mountain: 9, desert: 5 },
    },
  },
  {
    id: 'challenge-v2-11',
    name: '挑戰II·11 腹背受敵',
    builtin: true,
    settings: {
      rows: 24,
      columns: 24,
      baseCount: 2,
      nestCount: 5,
      resourcePointCount: 6,
      itemPointCount: 30,
      playerCount: 1,
      aiPlayerCount: 0,
      explorationEventCount: 0,
      explorationTriggerChance: 0,
      creatureCount: 16,
      ruinCount: 6,
      sectGateCount: 1,
      terrainWeights: { plain: 32, forest: 5, water: 5, mountain: 13, desert: 45 },
    },
  },
  {
    id: 'challenge-v2-12',
    name: '挑戰II·12 疲於奔命',
    builtin: true,
    settings: {
      rows: 24,
      columns: 24,
      baseCount: 2,
      nestCount: 6,
      resourcePointCount: 6,
      itemPointCount: 33,
      playerCount: 1,
      aiPlayerCount: 0,
      explorationEventCount: 0,
      explorationTriggerChance: 0,
      creatureCount: 18,
      ruinCount: 5,
      sectGateCount: 0,
      terrainWeights: { plain: 32, forest: 14, water: 7, mountain: 42, desert: 5 },
    },
  },
  {
    id: 'challenge-v2-13',
    name: '挑戰II·13 三城鼎立',
    builtin: true,
    settings: {
      rows: 26,
      columns: 26,
      baseCount: 3,
      nestCount: 6,
      resourcePointCount: 9,
      itemPointCount: 36,
      playerCount: 1,
      aiPlayerCount: 0,
      explorationEventCount: 0,
      explorationTriggerChance: 0,
      creatureCount: 19,
      ruinCount: 5,
      sectGateCount: 0,
      terrainWeights: { plain: 40, forest: 20, water: 10, mountain: 15, desert: 15 },
    },
  },
  {
    id: 'challenge-v2-14',
    name: '挑戰II·14 席捲而至',
    builtin: true,
    settings: {
      rows: 26,
      columns: 26,
      baseCount: 3,
      nestCount: 7,
      resourcePointCount: 9,
      itemPointCount: 39,
      playerCount: 1,
      aiPlayerCount: 0,
      explorationEventCount: 0,
      explorationTriggerChance: 0,
      creatureCount: 20,
      ruinCount: 4,
      sectGateCount: 0,
      terrainWeights: { plain: 36, forest: 12, water: 40, mountain: 7, desert: 5 },
    },
  },
  {
    id: 'challenge-v2-15',
    name: '挑戰II·15 蠻妖壓境',
    builtin: true,
    settings: {
      rows: 28,
      columns: 28,
      baseCount: 3,
      nestCount: 7,
      resourcePointCount: 9,
      itemPointCount: 42,
      playerCount: 1,
      aiPlayerCount: 0,
      explorationEventCount: 0,
      explorationTriggerChance: 0,
      creatureCount: 22,
      ruinCount: 4,
      sectGateCount: 0,
      terrainWeights: { plain: 30, forest: 48, water: 8, mountain: 9, desert: 5 },
    },
  },
  {
    id: 'challenge-v2-16',
    name: '挑戰II·16 節節敗退',
    builtin: true,
    settings: {
      rows: 28,
      columns: 28,
      baseCount: 3,
      nestCount: 8,
      resourcePointCount: 9,
      itemPointCount: 45,
      playerCount: 1,
      aiPlayerCount: 0,
      explorationEventCount: 0,
      explorationTriggerChance: 0,
      creatureCount: 24,
      ruinCount: 3,
      sectGateCount: 0,
      terrainWeights: { plain: 32, forest: 5, water: 5, mountain: 13, desert: 45 },
    },
  },
  {
    id: 'challenge-v2-17',
    name: '挑戰II·17 四面楚歌',
    builtin: true,
    settings: {
      rows: 30,
      columns: 30,
      baseCount: 4,
      nestCount: 9,
      resourcePointCount: 12,
      itemPointCount: 48,
      playerCount: 1,
      aiPlayerCount: 0,
      explorationEventCount: 0,
      explorationTriggerChance: 0,
      creatureCount: 25,
      ruinCount: 2,
      sectGateCount: 0,
      terrainWeights: { plain: 32, forest: 14, water: 7, mountain: 42, desert: 5 },
    },
  },
  {
    id: 'challenge-v2-18',
    name: '挑戰II·18 危城孤影',
    builtin: true,
    settings: {
      rows: 32,
      columns: 32,
      baseCount: 4,
      nestCount: 11,
      resourcePointCount: 12,
      itemPointCount: 51,
      playerCount: 1,
      aiPlayerCount: 0,
      explorationEventCount: 0,
      explorationTriggerChance: 0,
      creatureCount: 27,
      ruinCount: 2,
      sectGateCount: 0,
      terrainWeights: { plain: 26, forest: 22, water: 16, mountain: 20, desert: 16 },
    },
  },
  {
    id: 'challenge-v2-19',
    name: '挑戰II·19 大廈將傾',
    builtin: true,
    settings: {
      rows: 36,
      columns: 36,
      baseCount: 4,
      nestCount: 13,
      resourcePointCount: 12,
      itemPointCount: 54,
      playerCount: 1,
      aiPlayerCount: 0,
      explorationEventCount: 0,
      explorationTriggerChance: 0,
      creatureCount: 29,
      ruinCount: 1,
      sectGateCount: 0,
      terrainWeights: { plain: 26, forest: 22, water: 16, mountain: 20, desert: 16 },
    },
  },
  {
    id: 'challenge-v2-20',
    name: '挑戰II·20 五路圍攻',
    builtin: true,
    settings: {
      rows: 40,
      columns: 40,
      baseCount: 5,
      nestCount: 15,
      resourcePointCount: 15,
      itemPointCount: 58,
      playerCount: 1,
      aiPlayerCount: 0,
      explorationEventCount: 0,
      explorationTriggerChance: 0,
      creatureCount: 32,
      ruinCount: 0,
      sectGateCount: 0,
      terrainWeights: { plain: 22, forest: 20, water: 20, mountain: 24, desert: 14 },
    },
  },
]
