// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package uidata

import "fmt"

// KesStringListString is
func KesStringListString(dict map[string]ListString) []string {
	ret := make([]string, 0, len(dict))
	for k := range dict {
		ret = append(ret, k)
	}
	return ret
}

// ValsStringListString is
func ValsStringListString(dict map[string]ListString) []ListString {
	ret := make([]ListString, 0, len(dict))
	for _, v := range dict {
		ret = append(ret, v)
	}
	return ret
}

// MergeStringListString is
func MergeStringListString(a map[string]ListString, b map[string]ListString) map[string]ListString {
	ret := map[string]ListString{}
	for k, v := range a {
		ret[k] = v
	}
	for k, v := range b {
		ret[k] = v
	}
	return ret
}

// AssocStringListString is
func AssocStringListString(a map[string]ListString, k string, v ListString) map[string]ListString {
	ret := map[string]ListString{}
	for k, v := range a {
		ret[k] = v
	}
	ret[k] = v
	return ret
}

// DissocStringListString is
func DissocStringListString(a map[string]ListString, k string) map[string]ListString {
	ret := map[string]ListString{}
	for k, v := range a {
		ret[k] = v
	}
	delete(ret, k)
	return ret
}

func TryGetStringListString(a map[string]ListString, k string) (ListString, error) {
	ret, has := a[k]
	if has == false {
		return ret, fmt.Errorf("[TryGetStringListString] key not found: %v", k)
	}
	return ret, nil
}

func DifferenceStringListString(a map[string]ListString, b map[string]ListString) map[string]ListString {
	ret := map[string]ListString{}
	for k, v := range a {
		_, has := b[k]
		if has == false {
			ret[k] = v
		}
	}
	return ret
}
