// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package data

// KesStringPilot is
func KesStringPilot(dict map[string]Pilot) []string {
	ret := make([]string, 0, len(dict))
	for k := range dict {
		ret = append(ret, k)
	}
	return ret
}

// ValsStringPilot is
func ValsStringPilot(dict map[string]Pilot) []Pilot {
	ret := make([]Pilot, 0, len(dict))
	for _, v := range dict {
		ret = append(ret, v)
	}
	return ret
}

// MergeStringPilot is
func MergeStringPilot(a map[string]Pilot, b map[string]Pilot) map[string]Pilot {
	ret := map[string]Pilot{}
	for k, v := range a {
		ret[k] = v
	}
	for k, v := range b {
		ret[k] = v
	}
	return ret
}

// AssocStringPilot is
func AssocStringPilot(a map[string]Pilot, k string, v Pilot) map[string]Pilot {
	ret := map[string]Pilot{}
	for k, v := range a {
		ret[k] = v
	}
	ret[k] = v
	return ret
}
