services:
  # https://stackoverflow.com/questions/64247833/how-to-proxy-pass-api-path-to-port-with-nginx
  web:
    image: nginx:1.25
    volumes: 
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./public:/www/data
    ports:
      - 8080:8080